name: Render documents with rmarkdown-action
on:
  push:
    branches: [ master ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: diamonds.Rmd
	  output_format: html_document
