name: Render documents with rmarkdown-action
on:
  push:
    branches: [ master ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: diamonds.Rmd
	  output_format: html_document
